-- CoolingVerse 안양 평촌 지역 등록
-- 데이터 파이프라인이 pyeongchon 데이터를 적재하려면 districts 행이 먼저 있어야 한다.
-- oracle_loader.stage_and_activate()의 첫 문장인 data_pipeline_runs INSERT부터
-- fk_run_region이 districts(region_code)를 참조하므로, 행이 없으면 즉시 FK 위반이다.
-- 이어지는 grids MERGE도 (SELECT district_id FROM districts WHERE region_code=:1)로
-- district_id를 채우기 때문에 NULL이 되어 NOT NULL을 위반한다.

-- district_id를 6으로 명시한다. Regions.java의 PYEONGCHON districtId와 반드시 일치해야 하며
-- ScenarioStore.save()가 이 값을 scenarios.district_id FK로 그대로 사용한다.
-- 1~5는 PANGYO·INGYE·BUCHEON·SANBON·ILSAN이 점유하고 있다.
MERGE INTO districts d USING (SELECT 'pyeongchon' region_code FROM dual) s
ON (d.region_code = s.region_code)
WHEN NOT MATCHED THEN INSERT
  (district_id, name, region_code, display_name, is_active, sido, sigungu, center_lat, center_lng, is_base)
VALUES (6, '안양시 동안구', 'pyeongchon', '안양 평촌', 'Y', '경기도', '안양시 동안구', 37.3899, 126.9550, 'N');

-- district_id를 수동 지정했으므로 자동 번호를 재정렬한다 (AGENTS.md 절대규칙 5).
ALTER TABLE districts MODIFY (district_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
